[package]
name = "chessbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
reqwest = { version = "0.11.24", features = ["stream"] }
futures-io = { version = "0.2.0-beta" }
tokio-util = { version = "0.7.10", features = ["io"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
futures = "0.3.30"
tokio-macros = { version = "0.2.0-alpha.6" }
json = "0.12.4"
